ARG BASE_IMAGE=ubuntu:jammy
FROM ${BASE_IMAGE}
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y \
    build-essential cmake git sudo wget ninja-build \
    software-properties-common python3 python3-pip \
    gcc g++ gdb rsync tar x11-utils x11-apps zip \
    libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
    libgl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols \
    libegl1-mesa-dev libc++-dev libglew-dev libeigen3-dev \
    libboost-all-dev libssl-dev && \
    apt-get clean

COPY common/install_easy_profiler.sh /tmp/install_easy_profiler.sh
RUN bash /tmp/install_easy_profiler.sh && rm /tmp/install_easy_profiler.sh

COPY orb_slam2/src /Portable_ORB_SLAM2
RUN cd /Portable_ORB_SLAM2 && \
    python3 ./buildDeps.py && \
    python3 ./build.py --profiler

VOLUME /output
WORKDIR /Portable_ORB_SLAM2
