ARG BASE_IMAGE=docker.io/ros:noetic
FROM ${BASE_IMAGE}
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git wget ca-certificates ninja-build \
    libeigen3-dev libpcl-dev libopencv-dev \
    libboost-all-dev libgoogle-glog-dev libgflags-dev \
    libatlas-base-dev libsuitesparse-dev libtbb-dev \
    libspdlog-dev libfmt-dev \
    libglfw3-dev libglm-dev libpng-dev \
    libgtest-dev nlohmann-json3-dev \
    ros-noetic-cv-bridge ros-noetic-tf2-ros ros-noetic-rosbag \
    ros-noetic-pcl-ros ros-noetic-image-transport && \
    rm -rf /var/lib/apt/lists/*

# Install newer CMake (gtsam_points requires >= 3.22, noetic ships 3.16)
RUN CMAKE_ARCH=$(uname -m | sed 's/aarch64/aarch64/;s/x86_64/x86_64/') && \
    wget -qO- "https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake-3.28.3-linux-${CMAKE_ARCH}.tar.gz" | \
    tar xz -C /usr/local --strip-components=1

COPY common/install_easy_profiler.sh /tmp/install_easy_profiler.sh
RUN bash /tmp/install_easy_profiler.sh && rm /tmp/install_easy_profiler.sh

# Build GTSAM 4.2.0
RUN git clone https://github.com/borglab/gtsam.git -b 4.2.0 && \
    cd gtsam && mkdir build && cd build && \
    cmake .. -DGTSAM_BUILD_TESTS=OFF \
             -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF \
             -DGTSAM_USE_SYSTEM_EIGEN=ON \
             -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized -Wno-error=array-bounds" && \
    make -j$(nproc) && make install && ldconfig && \
    cd / && rm -rf gtsam

# Build iridescence
RUN git clone https://github.com/koide3/iridescence.git --recursive && \
    cd iridescence && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && make install && ldconfig && \
    cd / && rm -rf iridescence

# Build gtsam_points v1.0.0
RUN git clone https://github.com/koide3/gtsam_points.git -b v1.0.0 --recursive && \
    cd gtsam_points && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DBUILD_WITH_CUDA=OFF \
             -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized -Wno-error=array-bounds" && \
    make -j$(nproc) && make install && ldconfig && \
    cd / && rm -rf gtsam_points

# Build GLIM with profiler
COPY glim/src /glim
RUN cd /glim && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DBUILD_WITH_EASY_PROFILER=ON \
             -DBUILD_WITH_CUDA=OFF && \
    make -j$(nproc) && make install && ldconfig

# Build glim_ros1 (provides glim_rosbag offline processor)
RUN git clone https://github.com/koide3/glim_ros1.git

# Patch glim_rosbag.cpp to add easy_profiler init/dump + signal handler
COPY glim/profiler_patch.sh /tmp/profiler_patch.sh
RUN chmod +x /tmp/profiler_patch.sh && \
    /tmp/profiler_patch.sh /glim_ros1/src/glim_rosbag.cpp && \
    cd /glim_ros1 && \
    sed -i '/target_link_libraries(glim_rosbag/i find_package(easy_profiler REQUIRED)' CMakeLists.txt && \
    sed -i 's/target_link_libraries(glim_rosbag/target_link_libraries(glim_rosbag easy_profiler/' CMakeLists.txt && \
    mkdir build && cd build && \
    . /opt/ros/noetic/setup.sh && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-DBUILD_WITH_EASY_PROFILER" && \
    make -j$(nproc) && make install && ldconfig

VOLUME /output
WORKDIR /data

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
