ARG BASE_IMAGE=ros:noetic
FROM ${BASE_IMAGE}
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y \
    build-essential cmake git wget \
    libeigen3-dev libpcl-dev libusb-1.0-0-dev \
    ros-noetic-pcl-ros ros-noetic-eigen-conversions && \
    apt-get clean

COPY common/install_easy_profiler.sh /tmp/install_easy_profiler.sh
RUN bash /tmp/install_easy_profiler.sh && rm /tmp/install_easy_profiler.sh

RUN git clone https://github.com/Livox-SDK/Livox-SDK.git && \
    cd Livox-SDK && mkdir -p build && cd build && \
    cmake .. && make -j$(nproc) && make install && \
    cd / && rm -rf Livox-SDK

RUN mkdir -p /catkin_ws/src && cd /catkin_ws/src && \
    git clone https://github.com/Livox-SDK/livox_ros_driver.git && \
    git clone https://github.com/hku-mars/FAST_LIO.git && \
    cd FAST_LIO && git submodule update --init --recursive

COPY fast_lio2/patches/ /tmp/fastlio2_patches/
RUN cp /tmp/fastlio2_patches/CMakeLists.txt /catkin_ws/src/FAST_LIO/CMakeLists.txt && \
    cp /tmp/fastlio2_patches/laserMapping.cpp /catkin_ws/src/FAST_LIO/src/laserMapping.cpp && \
    cp /tmp/fastlio2_patches/preprocess.cpp /catkin_ws/src/FAST_LIO/src/preprocess.cpp && \
    cp /tmp/fastlio2_patches/IMU_Processing.hpp /catkin_ws/src/FAST_LIO/src/IMU_Processing.hpp

WORKDIR /catkin_ws
RUN . /opt/ros/noetic/setup.sh && \
    catkin_make -j$(nproc) -DCMAKE_BUILD_TYPE=Release -DWITH_PROFILER=ON

RUN sed -i "6i source \"/catkin_ws/devel/setup.bash\"" /ros_entrypoint.sh

VOLUME /output
WORKDIR /data
ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
